# Site settings
title: Wikia Style Guide
email: kenneth@wikia-inc.com
description: > # this means to ignore newlines until "baseurl:"
  The Wikia Style Guide package, common front end assets for projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Wikia
github_username: Wikia

# Build settings
markdown: kramdown
